steps:
  - name: golang:1.22
    entrypoint: /bin/bash
    args:
      - -c
      - |
        go install github.com/jstemmer/go-junit-report/v2@latest
        2>&1 go test -timeout 1m -v ./... | /go/bin/go-junit-report -set-exit-code -iocopy -out ${SHORT_SHA}_test_log.xml

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - func-a-$_ENV
      - --entry-point=HelloHTTP
      - --gen2
      - --region=australia-southeast1
      - --source=.
      - --trigger-http
      - --runtime=go121
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
