steps:
  - name: golang:1.22
    entrypoint: /bin/bash
    args:
      - go test -timeout 1m -v ./...

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - go-funcv2
      - --entry-point=$_ENTRY_POINT
      - --gen2
      - --region=$_REGION
      - --source=.
      - --trigger-http
      - --runtime=$_RUNTIME
      - --no-allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY

